Devops 343 create ecr module
nexient-llc/tf-aws-module-ecr pull request #1
Opened 2022-09-07 18:50 UTC by wright-nexient

Failing on build here:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/105006874/188955105-1f73e1be-735b-40d7-a9a0-ce39a0e2df20.png">

This is first PR... May have to make some changes in terratest... Generally I think the terraform itself is working.

Will not pass GHA as I don't think creds are configured in `.github`

2022-09-07 20:33 UTC, dsahoo-nexient requested changes

2022-09-07 20:33 UTC, dsahoo-nexient commented on README.md
Add License info

2022-09-07 20:33 UTC, dsahoo-nexient commented on outputs.tf
> +output "arn" {
Please add description for each output with a proper description of what the output means

2022-09-07 20:33 UTC, dsahoo-nexient commented on tests/post_deploy_functional/deploy_test.go
>  }
No real test cases found here. Can you add a test case to fetch the ecr repo created in AWS and verify against the expected name

2022-09-07 20:33 UTC, dsahoo-nexient commented on README.md
> +This module is used to create an ECR Repo with Lifecycle Policies
I think the name of the repo kind of doesn't match with the description. Shouldn't the repo name be ecr_repository or just ecr instead of ecr task?

2022-09-07 20:33 UTC, dsahoo-nexient commented on variables.tf
> +  description = ""
Please fill in the description for all missing ones. Also can you add question mark for all the descriptions that are questions like "How many days to keep untagged images"

2022-09-07 21:33 UTC, TheFynx commented on README.md
> +<!-- optional markdown-notes-tree directory description ends here -->
These can be removed
```suggestion
```

2022-09-09 15:26 UTC, wright-nexient commented on README.md
I have the badge for Apache2.0

2022-09-09 16:11 UTC, dsahoo-nexient approved these changes

2022-09-09 16:35 UTC, bignastybryce approved these changes

2022-09-09 16:43 UTC, merged